stages:
- test
- release

.test:
  stage: test
  before_script:
    - apt update
    - apt install -y libgl1-mesa-glx
    - pip install -r requirements-dev.txt

python37:
  extends: .test
  image: python:3.7
  script: tox -e py37

python38:
  extends: .test
  image: python:3.8
  script: tox -e py38

python39:
  extends: .test
  image: python:3.9
  script: tox -e py39

python310:
  extends: .test
  image: python:3.10
  script: tox -e py310

publish:
  stage: release
  image: python
  before_script:
    - apt update
    - apt install -y libgl1-mesa-glx
    - pip install -r requirements-dev.txt
  script:
    - python3 -m build --sdist
    - twine upload dist/*
  only:
    - tags